# Generated by Django 3.1.4 on 2022-01-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=500)),
                ('video_link', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
            ],
        ),
    ]
