# Generated by Django 3.1.4 on 2022-01-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('youtube_channel', models.URLField()),
                ('twitter_link', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
