# Generated by Django 3.1.4 on 2022-02-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('par', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
